# Generated by Django 2.2 on 2019-04-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0011_auto_20180424_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cache_ttl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='layout',
            field=models.CharField(default='plain', max_length=100),
        ),
    ]
