# Generated by Django 2.2 on 2019-04-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0012_auto_20190412_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='imgur_template',
            field=models.CharField(default='imgur', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='reddit_live_template',
            field=models.CharField(default='reddit_live.md', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='reddit_title_template',
            field=models.CharField(default='reddit_title', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='tweet_template',
            field=models.CharField(default='tweet', max_length=200),
        ),
    ]
