# Generated by Django 2.2 on 2019-04-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0013_auto_20190423_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='draft_year',
            field=models.IntegerField(default=2019),
        ),
    ]
